[package]
name = "monte_carlo_view_factors"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = {version = "0.23.0", features = ["glam-assert"]}
kiss3d = "0.35.0"
rand = "0.8.5"
rayon = "1.7.0"
